<?php

/**
 * @file
 * catering_menu_entity.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function catering_menu_entity_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_content_blocks'.
  $field_bases['field_content_blocks'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_content_blocks',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'paragraphs',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'paragraphs',
  );

  // Exported field_base: 'field_menu_disclaimer'.
  $field_bases['field_menu_disclaimer'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_menu_disclaimer',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
